server:
  port: 8080 # inside container port

history:
  service:
    server: 127.0.0.1
    port: 8081
# two docker containers with different outside ports (8080 from container mapped to 8081 machine)
# docker run -d -p 8080:8080 qrcode
# docker run -d -p 8081:8888 qrcode
# docker run -d -p <computer-port:container-port> qrcode